[package]
name = "crypto"
version = "0.1.0"
edition = "2024"

[dependencies]
chacha20 = "0.9"
cipher = "0.4"
rand = "0.9"
clap = { version = "4", features = ["derive"] }
argon2 = "0.5"
thiserror = "2.0.16"
